// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE1SXQTcilIVaAaEIqp22XIhdiTveb-Zo',
    appId: '1:1051218072946:web:2effa29380aec20bcd39eb',
    messagingSenderId: '1051218072946',
    projectId: 'quantified-services',
    authDomain: 'quantified-services.firebaseapp.com',
    databaseURL: 'https://quantified-services-default-rtdb.firebaseio.com',
    storageBucket: 'quantified-services.appspot.com',
    measurementId: 'G-0G6NZPJMMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxsbsNSIiuWgey9O041YsyHVj52AJOOug',
    appId: '1:1051218072946:android:1a52b54112e95431cd39eb',
    messagingSenderId: '1051218072946',
    projectId: 'quantified-services',
    databaseURL: 'https://quantified-services-default-rtdb.firebaseio.com',
    storageBucket: 'quantified-services.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0qI2DOYeaUY7ur7-ZblkJLbdkVKtIus0',
    appId: '1:1051218072946:ios:76a7578ea700c0f8cd39eb',
    messagingSenderId: '1051218072946',
    projectId: 'quantified-services',
    databaseURL: 'https://quantified-services-default-rtdb.firebaseio.com',
    storageBucket: 'quantified-services.appspot.com',
    iosClientId:
        '1051218072946-p8rr21nh5k1om4sp6kkagjnqbddifvgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantified',
  );
}
